networks:
  flwr_network:
    driver: bridge
services:
  client32:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client32
    cpus: 2
    cpuset: "31,32"
    depends_on:
      - server2
    environment:
      CLIENT_ID: '32'
      NUM_CPUS: '2'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server2:8081
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client33:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client2
    cpus: 2
    cpuset: "2,3"
    depends_on:
      - server
    environment:
      CLIENT_ID: '2'
      NUM_CPUS: '2'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client3
    cpus: 1
    cpuset: "4"
    depends_on:
      - server
    environment:
      CLIENT_ID: '3'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client4:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client4
    cpus: 1
    cpuset: "5"
    depends_on:
      - server
    environment:
      CLIENT_ID: '4'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client5:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client5
    cpus: 1
    cpuset: "6"
    depends_on:
      - server
    environment:
      CLIENT_ID: '5'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client6:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client6
    cpus: 1
    cpuset: "7"
    depends_on:
      - server2
    environment:
      CLIENT_ID: '33'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server2:8081
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client7:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client7
    cpus: 1
    cpuset: "8"
    depends_on:
      - server
    environment:
      CLIENT_ID: '7'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client8:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client8
    cpus: 1
    cpuset: "9"
    depends_on:
      - server
    environment:
      CLIENT_ID: '8'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client9:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client9
    cpus: 1
    cpuset: "10"
    depends_on:
      - server
    environment:
      CLIENT_ID: '9'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client10:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 20 && python client.py"
    container_name: Client10
    cpus: 1
    cpuset: "11"
    depends_on:
      - server
    environment:
      CLIENT_ID: '10'
      NUM_CPUS: '1'
      NUM_RAM: '4'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 4g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server2
    deploy:
      resources:
        limits:
          cpus: '0.5'
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: ${NUM_ROUNDS}
    networks:
    - flwr_network
    ports:
    - 8081:8081
    volumes:
    - ./data:/app/data
    - ./performance:/app/performance
    - ./configuration:/app/configuration
    - ./model_weights:/app/model_weights
    - .:/app
    - /var/run/docker.sock:/var/run/docker.sock
