networks:
  flwr_network:
    driver: bridge
services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client1
    cpus: 2
    cpuset: "0,1"
    depends_on:
      - server
    environment:
      CLIENT_ID: '1'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client2
    cpus: 2
    cpuset: "2,3"
    depends_on:
      - server
    environment:
      CLIENT_ID: '2'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client3
    cpus: 2
    cpuset: "4,5"
    depends_on:
      - server
    environment:
      CLIENT_ID: '3'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client4:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client4
    cpus: 2
    cpuset: "6,7"
    depends_on:
      - server
    environment:
      CLIENT_ID: '4'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client5:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client5
    cpus: 2
    cpuset: "8,9"
    depends_on:
      - server
    environment:
      CLIENT_ID: '5'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client6:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client6
    cpus: 2
    cpuset: "10,11"
    depends_on:
      - server
    environment:
      CLIENT_ID: '6'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client7:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client7
    cpus: 2
    cpuset: "12,13"
    depends_on:
      - server
    environment:
      CLIENT_ID: '7'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client8:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client8
    cpus: 2
    cpuset: "14,15"
    depends_on:
      - server
    environment:
      CLIENT_ID: '8'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client9:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client9
    cpus: 2
    cpuset: "16,17"
    depends_on:
      - server
    environment:
      CLIENT_ID: '9'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client10:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client10
    cpus: 2
    cpuset: "18,19"
    depends_on:
      - server
    environment:
      CLIENT_ID: '10'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client11:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client11
    cpus: 2
    cpuset: "20,21"
    depends_on:
      - server
    environment:
      CLIENT_ID: '11'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  client12:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: sh -c "sleep 5 && python client.py"
    container_name: Client12
    cpus: 2
    cpuset: "22,23"
    depends_on:
      - server
    environment:
      CLIENT_ID: '12'
      NUM_CPUS: '2'
      NUM_RAM: '2'
      NUM_ROUNDS: '20'
      SERVER_ADDRESS: server:8080
    labels:
      - type=client
    mem_limit: 2g
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    deploy:
      resources:
        limits:
          cpus: '0.5'
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: ${NUM_ROUNDS}
    networks:
    - flwr_network
    ports:
    - 8080:8080
    volumes:
    - ./data:/app/data
    - ./performance:/app/performance
    - ./configuration:/app/configuration
    - ./model_weights:/app/model_weights
    - .:/app
    - /var/run/docker.sock:/var/run/docker.sock
